/******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the HC-SR04 Ultrasonic sensor driver
 *
 * Author: Menna Saeed
 *
 *******************************************************************************/
#include "ultrasonic.h"
#include "icu.h"
#include "std_types.h"
#include "util/delay.h"
/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

static uint16 g_echo_time=0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description : Function to initialize the Ultrasonic sensor driver
 * 	1. Initialize the ICU driver as required. ->The ICU should be configured
 * 		with frequency F_CPU/8 and to detect the raising edge
 * 		as the first edge.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through the GPIO driver
 */

void Ultrasonic_init (void)
{
	/*Configure and initialize the ICU driver*/
	Icu_ConfigType Icu_config={F_CPU_8,RISING};
	Icu_init(&Icu_config);

	/*set the ICU call back function pointer in the ICU driver*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/*Setup the direction for the trigger pin as output pin through the GPIO driver*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, PIN_OUTPUT);
	GPIO_writePin(ULTRASONIC_TRIGGER_PIN, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}

/*
 * Description :
 * 				Send the Trigger pulse to the ultrasonic.
 */

void Ultrasonic_Trigger (void)
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_HIGH);
	_delay_us(ULTRASONIC_TRIGGER_PULSE);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}

/*
 * Description :
 * 				1- Send the trigger pulse by using Ultrasonic_Trigger function
 * 				2- Start the measurements by the ICU from this moment.
 */

uint16 Ultrasonic_readDistance (void)
{
	 Ultrasonic_Trigger();

	 /*
	  * Sound velocity = 340.00 m/s = 34000 cm/s
	  *
	  * Total Distance=Time*Speed
	  *
	  * Required distance=Total Distance/2
	  *
	  * Now, here we have selected an internal 8MHz oscillator frequency for ATmega16,
	  * with Prescaler F_CPU/8 for timer frequency. Then time to execute 1 instruction is 1 us.
	  * So, the timer gets incremented after 1 us time
	  *  = 17000 x (TIMER value) x 1 x 10^-6 cm = 0.017 x (TIMER value) cm
	  *  = (TIMER value) / 58.8 cm Note TIMER VALUE is the pulse width time calculated by the ICU.
	  */

	 uint16 total_distance;
	 total_distance=g_echo_time/58;
	 return ((total_distance));
}

/*
 * Description :
 * 				1- This is the call back function called by the ICU driver.
 * 				2- This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */

void Ultrasonic_edgeProcessing (void)
{
   static uint8 g_edgeCount = 0;
	g_edgeCount++;
		if(g_edgeCount == 1)
		{
			/*
			 * Clear the timer counter register to start measurements from the
			 * first detected rising edge
			 */
			Icu_clearTimerValue();
			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 2)
		{
			/* Store the High time value */
			g_echo_time = Icu_getInputCaptureValue();
			/* Detect rising edge */
			Icu_setEdgeDetectionType(RISING);

			g_edgeCount=0;
		}
}
