/******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the HC-SR04 Ultrasonic sensor driver.
 *
 * Author: Menna Saeed
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#include "gpio.h"
#include "std_types.h"

/* ULTRASONIC HW Ports and Pins IDs */
#define ULTRASONIC_ECHO_PORT     PORTD_ID
#define ULTRASONIC_ECHO_PIN      PIN6_ID

#define ULTRASONIC_TRIGGER_PORT  PORTB_ID
#define ULTRASONIC_TRIGGER_PIN   PIN5_ID

#define ULTRASONIC_TRIGGER_PULSE  10

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description : Function to initialize the Ultrasonic sensor driver
 * 	1. Initialize the ICU driver as required. ->The ICU should be configured
 * 		with frequency F_CPU/8 and to detect the raising edge
 * 		as the first edge.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init (void);

/*
 * Description :
 * 				Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger (void);

/*
 * Description :
 * 				1- Send the trigger pulse by using Ultrasonic_Trigger function
 * 				2- Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance (void);

/*
 * Description :
 * 				1- This is the call back function called by the ICU driver.
 * 				2- This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing (void);



#endif /* ULTRASONIC_H_ */
